apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://169.62.174.26:8001
  name: cluster.local
- cluster:
    insecure-skip-tls-verify: true
    server: https://redhatocp.wiprocms.com:8443
  name: redhatocp-wiprocms-com:8443
- cluster:
    certificate-authority: wipro-icpdemo/ca.pem
    server: https://169.62.174.26:8001
  name: wipro-icpdemo
contexts:
- context:
    cluster: cluster.local
    namespace: microclimate-demo-namespace
    user: admin
  name: cluster.local-context
- context:
    cluster: redhatocp-wiprocms-com:8443
    namespace: fedexistio
    user: arijit/redhatocp-wiprocms-com:8443
  name: fedexistio/redhatocp-wiprocms-com:8443/arijit
- context:
    cluster: wipro-icpdemo
    namespace: microclimate-icp-namespace
    user: wipro-icpdemo-user
  name: wipro-icpdemo-context
current-context: cluster.local-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiYXd6Z29wdXRhOWQwbmxtdWo5aXQiLCJyZWFsbU5hbWUiOiJjdXN0b21SZWFsbSIsInVuaXF1ZVNlY3VyaXR5TmFtZSI6ImFkbWluIiwiaXNzIjoiaHR0cHM6Ly93aXByby1pY3BkZW1vLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiIzZmI4MmY0NWY0NzE2YmJkY2ViMGI0YTA3NzFjNjFhNiIsImV4cCI6MTU2MTkzMjM0NSwiaWF0IjoxNTYxOTAzNTQ1LCJzdWIiOiJhZG1pbiIsInRlYW1Sb2xlTWFwcGluZ3MiOltdfQ.ZBc07PbmTRrxCws_L-4j-egkSDdBb0FB36atItYEI5sxNuFzxIIccCv_QECHTIWgZ2ZphRJzfKKfAyWLi2Vy9HVqxOcx4LcJrAbT2FTKm6PXr5QECCSv5pYKogXMLxePa2Np9nMFM4PwUgYyCmmuBIIMLOeAnpImSdXEcxlcp2bDQrjNj7bSy4D37yXCBFrS3L-Ynz0uecGNVQxz8TtUoPgGEFJfyyLs3n7UQatN1BZuyikKgniRmjgicAVRvrKK9otnV07viYcbMvCeesKvueqt3-in8iOjZo7qkOqvHxJb1wJ_Yyd-_yDCdEyZuecHDrMAc4a5HI_Hhe5iwx-QxQ
- name: arijit/redhatocp-wiprocms-com:8443
  user:
    token: 70HnqMVDC_7QXNbkJTwwRhAOvrNIvSiY5coQEZtRHLw
- name: wipro-icpdemo-user
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoicW4wNTR4NTc0d2pjd2dwZjRwbzgiLCJyZWFsbU5hbWUiOiJjdXN0b21SZWFsbSIsInVuaXF1ZVNlY3VyaXR5TmFtZSI6ImFkbWluIiwiaXNzIjoiaHR0cHM6Ly93aXByby1pY3BkZW1vLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiIzZmI4MmY0NWY0NzE2YmJkY2ViMGI0YTA3NzFjNjFhNiIsImV4cCI6MTU2MTU5OTk0NiwiaWF0IjoxNTYxNTcxMTQ2LCJzdWIiOiJhZG1pbiIsInRlYW1Sb2xlTWFwcGluZ3MiOltdfQ.GtlahB2C7vDF6coixbDizTDHb4C3dSV1d_QddN2BAXRHXUfKq1OS2Jm4cD-7ANm-_lJFnRODO1lnELDm4u2kBcRD8wnU29AMMLzaA5pwODoh85yHJsf8HQf4s64PNeTnFPoGNfHCdswQm7PfgDLESBrYjw8km4LBUqrQUBikzDM2jLP5QvGLcV_Lg4VzxyjPErvBOJCT3UitGarfLqqEpE54t8BBqGyAMHVGxO3u3e5Uqif7aKgGlu6fkryXonVufOaV-9WKcfGaPEkvYuhl3Ki9ucgV7IlVzocsamPgdFyNlDlZcBf1CB-lShPy3LYysnjNl6CxEDRuKumaMpSbIw
